sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10.5"
before_install:
  - npm i -g npm@^6.9.0
before_script:
  - npm prune
script:
  - npm run build
  - npm test
